export const techStack: string[] = [
    'React',
    'TypeScript',
    'JavaScript',
    'Next.js',
    'Vue.js',
    'Nuxt.js',
    'Redux Toolkit',
    'Vite',
    'Webpack',
    'Node.js',
    'Express',
    'PostgreSQL',
    'Docker',
    'REST API',
    'WebSocket',
    'MapLibre GL',
    'Tailwind CSS',
    'MUI',
    'SCSS',
    'HTML',
    'CSS',
    'Git',
    'Figma',
];
